### PR TITLE
added js file and question arrays, linked css file

### PR DESCRIPTION
**Pull request by HaiAsh**
-[linked css file]
-[added js file]
-[added Start Quiz button]
-[added quiz information on home page]
-[added array of questions and answers along with correct answers]

### CODE REVIEW

**Review by girma1978 — COMMENTED** [review]
reviewed

**Comment by girma1978** [comment]
reviewed

**Review by girma1978 — COMMENTED** [review]
reviewed

**Review by warrenwest — APPROVED** [review]
Reviewed

**Pull request merged**
